version: 1
disable_existing_loggers: no
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] %(module)s - %(message)s'
  normal:
    format: '[%(asctime)s] [%(levelname)s] %(name)s %(module)s - %(message)s'
  verbose:
    format: '[%(asctime)s] [%(levelname)s] %(module)s - %(message)s at %(filename)s line %(lineno)d'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: normal
    stream: ext://sys.stdout
loggers:
  app:
    handlers: [console]
root:
  level: DEBUG
  handlers: [console]
